#!/bin/sh
set -eu

CONFIG_FILE="${BROADCAST_BOX_CONFIG_FILE:-/etc/broadcast-box/broadcast-box.env}"
GENERATED_FILE="${BROADCAST_BOX_NAT_ENV_FILE:-/etc/broadcast-box/nat.env}"
SERVICE_NAME="${BROADCAST_BOX_SERVICE_NAME:-broadcast-box.service}"

read_env_value() {
	key="$1"
	file="$2"

	awk -F= -v key="$key" '
		$0 ~ /^[[:space:]]*($|#)/ { next }
		$1 == key {
			value = substr($0, length($1) + 2)
			gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
			if (value ~ /^".*"$/ || value ~ /^'\''.*'\''$/) {
				value = substr(value, 2, length(value) - 2)
			}
			print value
			exit
		}
	' "$file"
}

if [ ! -r "$CONFIG_FILE" ]; then
	echo "Broadcast Box config not readable: $CONFIG_FILE" >&2
	exit 0
fi

nat_host="$(read_env_value NAT_1_TO_1_HOST "$CONFIG_FILE" || true)"
if [ -z "$nat_host" ]; then
	exit 0
fi

new_ip="$(getent ahostsv4 "$nat_host" | awk '{ print $1; exit }')"
if [ -z "$new_ip" ]; then
	echo "Unable to resolve IPv4 A record for NAT_1_TO_1_HOST=$nat_host" >&2
	exit 1
fi

old_ip=""
if [ -r "$GENERATED_FILE" ]; then
	old_ip="$(read_env_value NAT_1_TO_1_IP "$GENERATED_FILE" || true)"
fi

if [ "$new_ip" = "$old_ip" ]; then
	exit 0
fi

generated_dir="$(dirname "$GENERATED_FILE")"
tmp_file="$(mktemp "$generated_dir/nat.env.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

cat > "$tmp_file" <<EOF
# Generated by broadcast-box NAT refresh watcher.
# Do not edit directly; set NAT_1_TO_1_HOST in $CONFIG_FILE.
NAT_1_TO_1_IP=$new_ip
EOF

chmod 0644 "$tmp_file"
mv "$tmp_file" "$GENERATED_FILE"
trap - EXIT

echo "Updated NAT_1_TO_1_IP from '${old_ip:-unset}' to '$new_ip'"

if command -v systemctl >/dev/null 2>&1; then
	systemctl try-restart "$SERVICE_NAME"
fi
